name: CI for Feature Branches

on:
  push:
    branches:
      - 'feature/*'   # Trigger on pushes to any feature branch
  pull_request:
    branches:
      - 'main'        # Trigger on pull requests to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'   # Use the Node.js version you want to work with

      - name: Install dependencies
        run: npm install         # Installs the dependencies defined in package.json
        

      - name: Start the application
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}    # Pass Supabase URL from secrets
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_KEY }}  # Pass Supabase API key from secrets
        run: npm start           # Run the start script
